### ISSUE TITLE
Copy of the game rules

### ISSUE THREAD

**Issue by CoderDennis** [lehoff/acquirex#2]
I grew up playing Acquire with my parents and their friends in the 70's and 80's. It's one of my favorite games, so I'm excited about jumping into this code and learning Elixir at the same time. My memory of the rules may not even be accurate with what was printed in the 1960's US version of the game because we may have played under some of our own house rules.

So, do you have a copy of the rules that you're basing this code on that could be used to make sure any contributions are following the same spec?

The Wikipedia page looks like it has a pretty good description. Is it an accurate enough listing of the rules? https://en.wikipedia.org/wiki/Acquire

**Comment by lehoff** [comment]
I think the official rules can be obtained here: 
http://www.boardgamecapital.com/acquire-rules.htm

They are the same as in my game...

And please open up discussions for how to deal with the mergers - starting with mscs (I should add the existing ones to the repo so that they are not only in the slide deck).
